### PR TITLE
Adding mac CI

### PR DESCRIPTION
**Pull request by daniellasry**
- [x] Added os clause specifying linux and osx
- [x] using macOS 10.13 VM (xcode 9.4)
- [x] moved all the apt-get installs to the addons clause (apt will be ignored on osx)
- [x] installing R via homebrew package
- [x] moving docker command under if statement (only run in linux)
- [x] added build command for osx only (same as linux but without docker)
- [x] changed malloc to new
- [x] upload to different aws folder on mac
- [x] removed unneeded R packages

will squash commits :)

### CODE REVIEW

**Comment by daniellasry** [comment]
I celebrated too soon. Looks like it broke when using older Mac OS

**Comment by Andrey1994** [comment]
I think we also need to upload Mac and Linux libraries to different S3 "folders" and download both of them in appveyour

**Comment by Andrey1994** [comment]
Seems like 
services: docker
doesnt work on Mac, but its crucial for linux. Let's try to install docker for linux only

Is it possible to use gcc instead clang with macos?

Should I configure smth in travis for my own version of brainflow to run it?

And let's add uploading/downloading to/from AWS

**Comment by daniellasry** [comment]
Docker is not installed on mac, it gets ignored.
There is a way to use gcc, i did it locally. I'll try that.

**Comment by daniellasry** [comment]
For your own brainflow you should be able to apply the same change as I did here.

**Comment by Andrey1994** [comment]
it looks good and finally works. 
Just need to update appveyour to download files for MacOS from S3 and push package to pypi. Let's add it, squash commits and release new minor version to test release pipeline(also in this version will be added daisy, synthetic board and MacOS)

**Comment by daniellasry** [comment]
@Andrey1994  should be complete now, although not sure how to test the deployment

**Pull request merged**
