### PR TITLE
change lib directory

### PR DESCRIPTION
**Pull request by Fan1117**
issue with matlab - it load library without specifing file extension, and without extension files for MacOS and Linux have the same name

### CODE REVIEW

**Comment by Andrey1994** [comment]
@daniellasry how did it work with MacOS with custom_command under if (UNIX) condition?

**Comment by Andrey1994** [comment]
@Fan1117  I guess you need to changes paths in BoardShim.m too

**Comment by Andrey1994** [comment]
Apple is a subset of unix and here it will not work because if(UNIX) condition is true for APPLE I think you need to change it to smth like if APPLE elseif(UNIX)

**Comment by Fan1117** [comment]
have changed if order and addpath in BoardShim.m. ready for merging!

**Comment by Andrey1994** [comment]
lets fix this PR

**Pull request closed without merging**
