### PR TITLE
added brainflow package name to java for import

### PR DESCRIPTION
**Pull request by daniellasry**
- Renamed brainflow-java.jar to brainflow.jar - OpenBCI GUI cannot import .jar with a "-" in the name.
- package .dlls in brainflow directory inside jar
- added ```package brainflow;``` to all java files, so you can ```import brainflow.*```
- replaced tabs with spaces

### CODE REVIEW

**Comment by Andrey1994** [comment]
- renaming - ok
- package .dlls - what do you mean here? In fact they are dlls in jar file after mvn build there are jar file(maybe two of them) and one of them contains compiled libraries, and there are required lines in pom.xml. But to load them - we need to extract dlls from jar
- package - nice
- spaces instead tabs - nice

**Comment by daniellasry** [comment]
to clarify #2: 

since all java files are part of the brainflow package now, in the jar file all the .class files are under a "brainflow" directory.

because of this, unpacking the dlls from the jar file was failing because it was looking the dlls inside the "brainflow" directory. ```getClass().getResourceAsStream (lib_name)``` would return null. All I did was move the .dll files inside the brainflow directory inside the jar. (line 19 in pom.xml)

**Comment by Andrey1994** [comment]
btw maybe we should remove compiled libraries from jar and force users to add them to search path by themself? It will be like our C#\C++ api

**Comment by daniellasry** [comment]
I'm fine with that, it's probably how other libraries do it.

Is there something wrong with putting the libraries in the jar? seems to work.

**Comment by daniellasry** [comment]
wow, i'm sorry, I really f'ed up this PR. might start over.

**Comment by Andrey1994** [comment]
when I checked it it was ok to me, so you can merge as soon as you fix all conflicts\CI....

**Pull request closed without merging**
