### PR TITLE
Config board

### PR DESCRIPTION
**Pull request by Andrey1994**
notable changes:

- add config_board method
- drop python2.7
- python should work with str and bytes objects

### CODE REVIEW

**Comment by daniellasry** [comment]
Looks good so far. I guess it's missing ganglion?

**Comment by Andrey1994** [comment]
Yep, appveyour test is failed because for ganglion it raises UNSUPPORTED_BOARD_ERROR for now, we can merge it as is and add ganglion later or add ganglion first.

Right now I have no access to ganglion board, so I can not add it

**Comment by daniellasry** [comment]
let's wait for ganglion so we don't break the CI

**Comment by Andrey1994** [comment]
will create new PR, smth went wrong with fixing merge conflicts

**Pull request closed without merging**
