### PR TITLE
added jars to aws for convenience

### PR DESCRIPTION
**Pull request by daniellasry**
Uplolading .jar files to aws to we can collect them from any build

### CODE REVIEW

**Comment by Andrey1994** [comment]
It will not work as you expect, it will not add jar files for all build, only for releases

**Comment by daniellasry** [comment]
thanks i will revise it

**Comment by daniellasry** [comment]
@Andrey1994 what do you think about this? It waits for mac and linux binaries on all builds, but only publishes to pypi and releases tab for new releases. Unfortunately this means all appveyor builds will take longer to complete.

**Comment by Andrey1994** [comment]
I think its okay, linux build failed due to bug in cmake from pypi I told you, lets fix it and test(already fixed in master)

**Comment by Andrey1994** [comment]
I think we can not add jar files to github page and aws as is, since they are built for java 7 right now which is dead and not supported. And we can not build it for all versions of java because its too long

So we have two options:

- completely remove jar files from github page and aws
- move to java 11 because its the latest LTS version but I am not sure that GUI uses java 11...

**Comment by Andrey1994** [comment]
@daniellasry  seems like this PR broke appveyour: https://ci.appveyor.com/project/daniellasry/brainflow/branch/master

**Comment by daniellasry** [comment]
weird, appveyor passed before i merged

**Comment by daniellasry** [comment]
possibly a bad merge with master. checking...

**Pull request merged**
