### PR TITLE
try to fix ganglion on ubuntu

### PR DESCRIPTION
**Pull request by Andrey1994**
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

Try harder to fix https://github.com/Andrey1994/brainflow/issues/24
I guess that its the reason for a failure on ubuntu:
```
        // dirty hack to solve https://github.com/Andrey1994/brainflow/issues/24
        // for Ubuntu callbacks for config_board are not triggered often if streaming is running.
        // Assumption - maybe serial buffer size is smaller in Ubuntu and notification messages fill
        // entire buffer. Solution for this assumption - call ble_cmd_attclient_attribute_write all
        // the time in the thread instead single invocation.
        // No idea about value for serial buffer size, educated guess - maybe its equal to page
        // size(4kb) and no idea about ways to check/change it
```
I dont find decent solution and still not sure that its an actual reason.
This fix is like brute force sending "s" and seems like on Ubuntu it does the trick
But for some reason it doesnt work on MSVC. After several hours with VS Debugger I still dont understand whats wrong with it.(and its not consistent across languages)
So another dirty hack - for MSVC and MacOS use code as before and add this trick under
```
#ifdef __linux__
```
Also I fixed timestamps for some reason I casted them to long before and back to double, its absolutely wrong.

### CODE REVIEW

**Comment by Andrey1994** [comment]
@retiutut Could you test it too? I run it on Fedora/Windows/Ubuntu, looks like now its much better in terms of robustness(in terms of code much worse). But since BLE and underlying library are not stable it makes sense to run a few more times on other machines(specially on MacOS).

From time to time callbacks for discovery or start_streaming are not triggered but its not under our control and we can not restart everything all the time if Ganglion or BGLIB does smth wrong. Even now code is full of workarounds in case if somewhere else everything is broken.

**Comment by retiutut** [comment]
```
retiutut@retiutut-MS-7893:~/Documents/Github/brainflow$ cd python-package
retiutut@retiutut-MS-7893:~/Documents/Github/brainflow/python-package$ python3 -m pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/retiutut/Documents/Github/brainflow/python-package
Requirement already satisfied: numpy in /home/retiutut/.local/lib/python3.6/site-packages (from brainflow==1.0.8) (1.16.3)
Installing collected packages: brainflow
  Attempting uninstall: brainflow
    Found existing installation: brainflow 1.0.8
    Uninstalling brainflow-1.0.8:
      Successfully uninstalled brainflow-1.0.8
  Running setup.py develop for brainflow
Successfully installed brainflow-1.0.8
retiutut@retiutut-MS-7893:~/Documents/Github/brainflow/python-package$ python3 /home/retiutut/Documents/Github/brainflow/tests/python/brainflow_get_data.py --board-id 1 --serial-port /dev/ttyACM0 --log 
[2020-02-17 14:55:26.843] [brainflow_logger] [info] incomming json: {
    "ip_address": "",
    "ip_port": 0,
    "ip_protocol": 0,
    "mac_address": "",
    "other_info": "",
    "serial_port": "/dev/ttyACM0"
}
[2020-02-17 14:55:26.843] [brainflow_logger] [debug] ganglionlib initialized
[2020-02-17 14:55:26.843] [brainflow_logger] [info] mac address is not specified, try to find ganglion without it
[2020-02-17 14:55:29.435] [brainflow_logger] [debug] use stub streamer
[2020-02-17 14:55:29.918] [brainflow_logger] [debug] start streaming
[2020-02-17 14:55:40.095] [brainflow_logger] [error] failed to stop streaming 13
Traceback (most recent call last):
  File "/home/retiutut/Documents/Github/brainflow/tests/python/brainflow_get_data.py", line 52, in <module>
    main ()
  File "/home/retiutut/Documents/Github/brainflow/tests/python/brainflow_get_data.py", line 45, in main
    board.stop_stream ()
  File "/home/retiutut/.local/lib/python3.6/site-packages/brainflow/board_shim.py", line 733, in stop_stream
    raise BrainFlowError ('unable to stop streaming session', res)
brainflow.board_shim.BrainFlowError: GENERAL_ERROR:17 unable to stop streaming session
retiutut@retiutut-MS-7893:~/Documents/Github/brainflow/python-package$ ^C
retiutut@retiutut-MS-7893:~/Documents/Github/brainflow/python-package$ /home/retiutut/Documents/Github/brainflow/tests/cpp/get_data_demo/brainflow_get_data --board-id 1 --serial-port /dev/ttyACM0 --log
[2020-02-17 14:56:01.654] [brainflow_logger] [info] incomming json: {"ip_address":"","ip_port":0,"ip_protocol":0,"mac_address":"","other_info":"","serial_port":"/dev/ttyACM0"}
[2020-02-17 14:56:01.654] [brainflow_logger] [debug] ganglionlib initialized
[2020-02-17 14:56:01.654] [brainflow_logger] [info] mac address is not specified, try to find ganglion without it
[2020-02-17 14:56:04.193] [brainflow_logger] [debug] use stub streamer
[2020-02-17 14:56:34.331] [brainflow_logger] [error] failed to start streaming 15
[2020-02-17 14:56:34.331] [brainflow_logger] [error] failed to start stream17
```

**Comment by Andrey1994** [comment]
As I told ganglion sometimes doesnt send ack for start streaming

**Comment by retiutut** [comment]
I cannot seem to run brainflow_get_data in Python or C++ tests on Ubuntu with Ganglion. I have tried many times this morning.


I am able to run brainflow_get_data using BLED112 dongle and Mac from branch `ganglion_ubuntu`.


```
Richard-Waltmans-iMac-3:brainflow Richard$ tests/cpp/get_data_demo/build/brainflow_get_data --board-id 1 --serial-port  /dev/cu.usbmodem11
[2020-02-17 14:48:10.115] [brainflow_logger] [info] incomming json: {"ip_address":"","ip_port":0,"ip_protocol":0,"mac_address":"","other_info":"","serial_port":"/dev/cu.usbmodem11"}
[2020-02-17 14:48:10.115] [brainflow_logger] [debug] ganglionlib initialized
[2020-02-17 14:48:10.115] [brainflow_logger] [info] mac address is not specified, try to find ganglion without it
[2020-02-17 14:48:12.746] [brainflow_logger] [debug] use stub streamer
[2020-02-17 14:48:13.021] [brainflow_logger] [debug] start streaming
[2020-02-17 14:48:13.021] [brainflow_logger] [info] Start sleeping in the main thread
[2020-02-17 14:48:18.173] [brainflow_logger] [info] read 719 packages

Data from the board

Total Channels for this board: 9
Channel 0: 115,115,116,116,117,
Channel 1: 6.15962,0.718061,5.72579,5.21716,-1.99711,
Channel 2: 4.87309,-1.27905,3.27615,3.91194,1.12571,
Channel 3: 7.23671,-4.05031,-0.845217,5.99132,-0.74798,
Channel 4: 3.796,-0.553505,8.0707,0.74798,1.51466,
Channel 5: 0,0,0,0,0,
Channel 6: 0,0,0,0,0,
Channel 7: 0,0,0,0,0,
Channel 8: 1.58197e+09,1.58197e+09,1.58197e+09,1.58197e+09,1.58197e+09,
```

**Pull request merged**
